### ISSUE TITLE
Missing Dockerfile for analyzer service

### ISSUE THREAD

**Issue by Chumper** [joe-io/kicking-it-with-kubernetes#2]
The analyzer services is missing a Dockerfile and it is not described on how to create it.

**Comment by shagreel** [comment]
That was on purpose. The goal was to use this as an exercise. To use what we learned from the api Dockerfile to build the analyzer Dockerfile. It ended up that we didn't have enough time to get into it in detail though. We will add a final version over everything soon so there is a completed version that you can look at.
